// =================================================================================
// This bucket is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cloud/internal/dao/internal"
)

// spaceUserDao is the data access object for the table space_user.
// You can define custom methods on it to extend its functionality as needed.
type spaceUserDao struct {
	*internal.SpaceUserDao
}

var (
	// SpaceUser is a globally accessible object for table space_user operations.
	SpaceUser = spaceUserDao{internal.NewSpaceUserDao()}
)

// Add your custom methods and functionality below.
