// =================================================================================
// This bucket is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cloud/internal/dao/internal"
)

// spaceDao is the data access object for the table space.
// You can define custom methods on it to extend its functionality as needed.
type spaceDao struct {
	*internal.SpaceDao
}

var (
	// Space is a globally accessible object for table space operations.
	Space = spaceDao{internal.NewSpaceDao()}
)

// Add your custom methods and functionality below.
